import { EventEmitter, ElementRef, NgZone, OnInit } from '@angular/core';
import { ImageSource, PinturaEditorOptions, PinturaEditor } from 'pintura';
export declare abstract class PinturaEditorAbstractComponent<T> implements OnInit {
    protected element: ElementRef;
    protected editor: PinturaEditor;
    protected zone: NgZone;
    private unsubs;
    src: ImageSource;
    options: PinturaEditorOptions;
    loadstart: EventEmitter<T>;
    loadabort: EventEmitter<T>;
    loaderror: EventEmitter<T>;
    loadprogress: EventEmitter<T>;
    load: EventEmitter<T>;
    processstart: EventEmitter<T>;
    processabort: EventEmitter<T>;
    processerror: EventEmitter<T>;
    processprogress: EventEmitter<T>;
    process: EventEmitter<T>;
    update: EventEmitter<T>;
    undo: EventEmitter<T>;
    redo: EventEmitter<T>;
    revert: EventEmitter<T>;
    destroy: EventEmitter<T>;
    show: EventEmitter<T>;
    hide: EventEmitter<T>;
    close: EventEmitter<T>;
    ready: EventEmitter<T>;
    loadpreview: EventEmitter<T>;
    addshape: EventEmitter<T>;
    selectshape: EventEmitter<T>;
    updateshape: EventEmitter<T>;
    removeshape: EventEmitter<T>;
    constructor(element: ElementRef, zone: NgZone);
    private routeEvent;
    abstract initEditor(element: HTMLElement, props: PinturaEditorOptions): PinturaEditor;
    ngAfterViewInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    ngOnInit(): void;
}
